apiVersion: v1
kind: Service
metadata:
  name: finegrtips-assignment-service
spec:
  selector:
    app: fingertips-app
  ports:
    - protocol: "TCP"
      port: 7777
      targetPort: 6996
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finegrtips-assignment
spec:
  selector:
    matchLabels:
      app: fingertips-app
  replicas: 1
  template:
    metadata:
      labels:
        app: fingertips-app
    spec:
      containers:
        - name: finegrtips-assignment
          image: fingertips_assignment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6996
